### JSON

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('train.json')
df.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

##### Importing json from url

In [3]:
df = pd.read_json('https://v6.exchangerate-api.com/v6/485ebc10da1cfbb273f72a6e/latest/USD')
df.head()

,result,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,base_code,conversion_rates
USD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1771632002,"Sat, 21 Feb 2026 00:00:02 +0000",1771718402,"Sun, 22 Feb 2026 00:00:02 +0000",USD,1.0000
AED,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1771632002,"Sat, 21 Feb 2026 00:00:02 +0000",1771718402,"Sun, 22 Feb 2026 00:00:02 +0000",USD,3.6725
AFN,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1771632002,"Sat, 21 Feb 2026 00:00:02 +0000",1771718402,"Sun, 22 Feb 2026 00:00:02 +0000",USD,62.9091
ALL,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1771632002,"Sat, 21 Feb 2026 00:00:02 +0000",1771718402,"Sun, 22 Feb 2026 00:00:02 +0000",USD,81.7661
AMD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1771632002,"Sat, 21 Feb 2026 00:00:02 +0000",1771718402,"Sun, 22 Feb 2026 00:00:02 +0000",USD,376.9643

### Working with SQL

In [4]:
import mysql.connector

In [5]:
conn = mysql.connector.connect(
    host= 'localhost',
    user='root',
    password='',
    database='world'
)

In [8]:
df  = pd.read_sql_query('SELECT * FROM country WHERE Region = "Caribbean"',conn)

C:\Users\Mohammad Tofik\AppData\Local\Temp\ipykernel_19940\2788711081.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df  = pd.read_sql_query('SELECT * FROM country WHERE Region = "Caribbean"',conn)

In [9]:
df.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
3,ATG,Antigua and Barbuda,North America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63,AG
4,BHS,Bahamas,North America,Caribbean,13878.0,1973.0,307000,71.1,3527.0,3347.0,The Bahamas,Constitutional Monarchy,Elisabeth II,148,BS