#### Importing pandas

In [ ]:
import pandas as pd

#### Opening Local CSV file

In [ ]:
df = pd.read_csv('aug_train.csv')
df.head()

#### Opening CSV file using URL

In [ ]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url,headers=headers)
data = StringIO(req.text)
df = pd.read_csv(data)
df.head()

#### sep parameter

In [20]:
df = pd.read_csv('movie_titles_metadata.tsv')
df.head()

  m0\t10 things i hate about you\t1999\t6.90\t62847\t['comedy' 'romance']
0  m1\t1492: conquest of paradise\t1992\t6.20\t10...
1  m2\t15 minutes\t2001\t6.10\t25854\t['action' '...
2  m3\t2001: a space odyssey\t1968\t8.40\t163227\...
3  m4\t48 hrs.\t1982\t6.90\t22289\t['action' 'com...
4  m5\tthe fifth element\t1997\t7.50\t133756\t['a...

In [21]:
df = pd.read_csv('movie_titles_metadata.tsv',sep='\t')
df.head()

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...

In [ ]:
df = pd.read_csv('movie_titles_metadata.tsv',sep='\t',names=['SNO','NAME','RELEASED_YEAR','RATING','NO OF REVIEWS','GENRE'])
df.head()

#### 5 index col parameter

In [ ]:
pd.read_csv('aug_train.csv').head()

In [ ]:
# here we default panda series and enrollee_id. both are same so we use index col parameter and convert enrollee_id to index

pd.read_csv('aug_train.csv',index_col='enrollee_id').head()

#### Header Parameter

In [ ]:
pd.read_csv('test.csv').head()

In [ ]:
# sometimes our header becomes 1st row so to handle this we can do this

pd.read_csv('test.csv',header=1).head()

#### 7 use cols parameter

In [ ]:
# sometime in ML we have to use a few cols among the all data set so we use use col parameter

pd.read_csv('aug_train.csv',usecols=['enrollee_id']).head()

#### 8 squeeze parameter

In [ ]:
# squeeze is used to convert dataframe to series when we have only one column

pd.read_csv('aug_train.csv',usecols=['enrollee_id']).squeeze().head()

#### 9 skiprows/nrows parameter

In [ ]:
# If we want to skip some rows we can use skiprows parameter

pd.read_csv('test.csv',header=1,skiprows=[1,3]).head()

In [ ]:
# If we want to use only few rows we can use nrows parameter
# It is mostly used in ML when we are dealing with large data set and we want to use only few rows for training our model and our RAM is not sufficient to handle large data set

pd.read_csv('aug_train.csv',nrows=100)

#### 10 Encoding Parameter

In [ ]:
# Generally encoding parameter of data is utf-8 but sometimes it is not the case and we have to use other encoding like latin-1, iso-8859-1 etc. like emoji dataset and other language dataset so to handle this we can use encoding parameter


pd.read_csv('zomato.csv').head()

In [ ]:
# this error we get "UnicodeDecodeError Traceback (most recent call last" because of encoding issue so to handle this we can use encoding parameter

pd.read_csv('zomato.csv',encoding='latin-1').head()

#### 11 skip bad lines

In [ ]:
# sometime in dataset some rows have more values than the number of columns so to handle this we can use error bad lines parameter

# for example in zomato dataset some rows have more values than the number of columns so to handle this we can use error bad lines parameter

pd.read_csv('zomato.csv', encoding='latin-1', on_bad_lines='warn').head()

#### dtypes parameter

In [ ]:
# when we use read_csv function it automatically detect data types of columns but sometime it is not the case and we have to specify data types of columns so to handle this we can use dtype parameter 

# for example in our 'aug_train.csv dataset target column has only 0 and 1 values but it is in float data type so to handle this we can use dtype parameter and convert it to int data type

# Syntax : dtype = {'column_name':data_type}

pd.read_csv('aug_train.csv',dtype={'target':int}).info()

#### 13 Handling Dates

In [ ]:
# when we have date column in our dataset it is in object data type so to handle this we can use parse date parameter and convert it to datetime data type

# for example in our 'IPL Matches 2008-2020.csv' we have date column in object data type so to handle this we can use parse date parameter and convert it to datetime data type

pd.read_csv("IPL Matches 2008-2020.csv").info()

# date             816 non-null    object

In [ ]:
# now we use parse date parameter and convert it to datetime data type

# syntax : parse_dates = ['column_name']
pd.read_csv("IPL Matches 2008-2020.csv",parse_dates=['date']).info()

# output would be like this
# 2   date             816 non-null    datetime64[ns]


# Now we can perform all the date time operations on date column like extracting year, month, day, day name, month name etc. because it is in datetime data type now


# if we have like month , day ,and year columns in our dataset and we want to combine them and convert them to datetime data type so to handle this we can use list of lists in parse date parameter

# syntax [[columns_numbers]]

# example : pd.read_csv("dataset_name",parse_dates=[[1,2,3]]).info()

#### 14  convertors

In [ ]:
def rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name

In [ ]:
# when we want to apply some transformation on our dataset before loading it to our dataframe we can use converters parameter

# for example in our IPL Matches 2008-2020 dataset we have team1 and team2 columns which have names like this "Royal Challengers Bangalore" and "Sunrisers Hyderabad" but i want like this "RCB" and "SRH" so to handle this we can use converters parameter and apply lambda function to extract first word from team1 and team2 columns

pd.read_csv("IPL Matches 2008-2020.csv",converters={
    'team1' : rename
}).head()

#### 15 na_values parameter

In [ ]:
# na_values parameter is used to handle missing values in our dataset
# for example in our 'aug_train.csv' dataset we have some missing values in city column which are represented by -1 so to handle this we can use na_values parameter and replace -1 with NaN

pd.read_csv('aug_train.csv',na_values=['city_21'])

#### 16 Loading a huge dataset in chunks

In [18]:
# sometime we get a huge dataset and our machine RAM is not sufficient to handle it so to handle this we can use chunksize parameter and read the dataset in chunks.
# we can specify the number of rows we want to read in each chunk using chunksize parameter 
# to access each chunk we can use for loop and iterate through each chunk and perform operations on it


dfs = pd.read_csv('aug_train.csv',chunksize=5000)

In [19]:
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)